name: "Main"

on:
  push:
    branches-ignore: ["test*"]

jobs:
  source-code-analysis:
    uses: Drastyn/actions/.github/workflows/source-code-analysis.yml@main
    with:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


