name: "Main"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout project'
        uses: actions/checkout@v4
      
      - name: 'Set up Java 11'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: 'Build project'
        shell: bash
        run: |
          chmod +x mvnw
          ./mvnw compile  
